apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability
# These labels are added to all configmaps and secrets.
generatorOptions:
  labels:
    grafana_dashboard: "1"

configMapGenerator:

- name: bootstrap-dashboards
  files:
    - _json/bootstrap/argocd.json
  options:
    annotations:
      k8s-sidecar-target-directory: "/tmp/dashboards/bootstrap"
- name: system-dashboards
  files:
    - _json/system/nginx.json
    - _json/system/loki-nginx.json
    - _json/system/jaeger.json
    - _json/system/cert-manager.json
  options:
    annotations:
      k8s-sidecar-target-directory: "/tmp/dashboards/system"
- name: platform-dashboards
  files:
    - _json/platform/argo-workflow.json
    - _json/platform/vault.json
  options:
    annotations:
      k8s-sidecar-target-directory: "/tmp/dashboards/platform"
    
