apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability
# These labels are added to all configmaps and secrets.
generatorOptions:
  labels:
    grafana_dashboard: "1"

configMapGenerator:
- name: platform-dashboards
  files:
    - _json/platform/argocd.json
    - _json/platform/nginx.json
  options:
    annotations:
      k8s-sidecar-target-directory: "/tmp/dashboards/platform"
